---
title: "Peat literature overview"
author: "Matt"
date: "6 9 2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Load the required packages
library(tidyverse)
library(bibliometrix)
library(here)
#load all the results in one large object
filelist=list.files(paste0(here::here(),"/data/"), pattern = ".txt",full.names = TRUE)
M <- convert2df(c(filelist[1],filelist[2],filelist[3],filelist[4],filelist[5],filelist[6],filelist[7],filelist[8],filelist[9],filelist[10],
                  filelist[11],filelist[12],filelist[13],filelist[14],filelist[15],filelist[16],filelist[17],filelist[18],filelist[19],filelist[20],filelist[21], filelist[22]), dbsource = "wos", format = "plaintext")

results <- biblioAnalysis(M, sep = ";")
```

## Introduction 

Co-word analysis identifies the most frequently used or co-occurring set of terms within a group of documents, which can reveal important concepts in a research field.

```{r, echo=FALSE, message=FALSE, warning=FALSE}

#S <- summary(object = results, k = 10, pause = FALSE)

Authorkeywords=results$DE
keywordPlus=results$ID

Authorkeywords=as_tibble(Authorkeywords)
keywordPlus=as_tibble(keywordPlus)

#wordcloud2::wordcloud2(Authorkeywords)
wordcloud2::wordcloud2(keywordPlus)


#bibliometrix::duplicatedMatching(M)

# Create keyword co-occurrences network
#NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

# full network
#net=networkPlot(NetMatrix, normalize="association", weighted=T, n =  100 , Title = "Keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,label= TRUE)

# Individual searches 


```

## Agriculture

```{r, include=FALSE}
M <- convert2df(c(filelist[1]), dbsource = "wos", format = "plaintext")
results <- biblioAnalysis(M, sep = ";")
S <- summary(object = results, k = 10, pause = FALSE)

```


```{r, echo=FALSE}
# Create keyword co-occurrences network
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

net=networkPlot(NetMatrix, normalize="association", weighted=T, n =  600 , Title = "'Agriculture': keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,label= FALSE)
```

## Carbon Accounting

```{r, include=FALSE}

M <- convert2df(c(filelist[2], filelist[3]), dbsource = "wos", format = "plaintext")
results <- biblioAnalysis(M, sep = ";")
S <- summary(object = results, k = 10, pause = FALSE)

```


```{r, echo=FALSE}
# Create keyword co-occurrences network
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

net=networkPlot(NetMatrix, normalize="association", weighted=T, n =  600 , Title = "'Carbon Accounting': keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,label= FALSE)
```

## Climate change

```{r, include=FALSE}

M <- convert2df(c(filelist[4], filelist[5]), dbsource = "wos", format = "plaintext")
results <- biblioAnalysis(M, sep = ";")
S <- summary(object = results, k = 10, pause = FALSE)

```


```{r, echo=FALSE}
# Create keyword co-occurrences network
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

net=networkPlot(NetMatrix, normalize="association", weighted=T, n =  600 , Title = "'Climate Change': keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,label= FALSE)
```

## Subsampling of each group

```{r,fig.show=FALSE, results='hide'}
NetMatrix <- biblioNetwork(M, analysis = "co-occurrences", network = "keywords", sep = ";")

net=networkPlot(NetMatrix, normalize="association", weighted=T, n =  length(M$TI) , Title = "'Climate Change': keyword Co-occurrences", type = "fruchterman", size=T,edgesize = 5,label= FALSE)



```

```{r, echo=FALSE}
out=data.frame(Title=M$TI,cluster=net$cluster_obj$membership)

cluster=as_tibble(out)

cluster %>% 
  group_by(cluster) %>% 
  sample_frac(.,size = 0.2,weight=NULL) %>% 
  kableExtra::kable() %>% 
  kableExtra::kable_styling()
```

## Gas exchange

```{r, include=FALSE}
M <- convert2df(c(filelist[11], filelist[12]), dbsource = "wos", format = "plaintext")

```

```{r, fig.show=FALSE}
source(paste0(here::here(),"/R/SubSample.R"))
SubSample(M,size=0.2)
```

